version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 22
    commands:
      - pip install uv
      - cd app-lib && uv sync && cd ..

  pre_build:
    commands:
      - make -f scripts/test.mk test

  build:
    commands:
      - make -f scripts/build.mk build
      - make -f scripts/deploy.mk deploy

  post_build:
    commands:
      - make -f scripts/post-deploy.mk post-deploy
