# Build targets for react-rest-lambda pattern
# Generated by /ipa.compose — do not edit manually
#
# Usage:
#   make -f scripts/build.mk build          # Build all artifacts
#   make -f scripts/build.mk build-{target} # Build single artifact

-include .env
include scripts/util/docker.mk

.PHONY: build

build:
	@echo "No build targets for this pattern"
