# Build targets for react-rest-lambda + sqs-lambda pattern
# Generated by /ipa.compose — do not edit manually
#
# Usage:
#   make -f scripts/build.mk build          # Build all artifacts
#   make -f scripts/build.mk build-fn       # Build single artifact

-include .env
export
include scripts/util/docker.mk

# Resolve version from app-lib/pyproject.toml + git SHA
IMAGE_TAG := $(shell python3 scripts/util/version.py docker)
APP_VERSION := $(shell python3 scripts/util/version.py version)
BUILD_VERSION := $(shell python3 scripts/util/version.py sha)

.PHONY: build build-fn build-frontend

build: build-fn build-frontend

build-fn:
	$(call ecr-login)
	$(call docker-build-push,$(APP_NAMESPACE)-$(APP_ENV)-fn,infra/containers/rest-lambda/Dockerfile,.,$(ECR_REGISTRY)/$(APP_NAMESPACE)-$(APP_ENV)-ecr,$(IMAGE_TAG),$(APP_VERSION),$(BUILD_VERSION))

build-frontend:
	cd web-client && npm ci && npm run build
