# Build targets for react-rest-lambda pattern
# Generated by /ipa.compose — do not edit manually
#
# Usage:
#   make -f scripts/build.mk build          # Build all artifacts
#   make -f scripts/build.mk build-fn       # Build single artifact

-include .env
export
include scripts/util/docker.mk

.PHONY: build build-fn

build: build-fn

build-fn:
	$(call ecr-login)
	$(call docker-build-push,$(APP_NAMESPACE)-$(APP_ENV)-fn,Dockerfile,.,$(ECR_REGISTRY)/$(APP_NAMESPACE)-$(APP_ENV)-ecr)
