# Deploy targets for react-rest-lambda + sqs-lambda pattern
# Generated by /ipa.compose — do not edit manually
#
# Usage:
#   make -f scripts/deploy.mk deploy            # Deploy all stacks
#   make -f scripts/deploy.mk deploy-queue       # Deploy single stack
#   make -f scripts/deploy.mk teardown           # Delete all stacks (reverse order)
#
# Variable resolution:
#   Local:  -include .env loads values from file
#   CI/CD:  -include silently skips; Make inherits env vars from CodeBuild

-include .env
export

# Resolve version from app-lib/pyproject.toml + git SHA
IMAGE_TAG := $(shell python3 scripts/util/version.py docker)

# Derive account hash for globally-unique identifiers (e.g., Cognito domain prefix)
APP_ACCOUNT_HASH := $(shell echo -n "$(AWS_ACCOUNT_ID)" | shasum | cut -c1-8)

.PHONY: deploy deploy-queue deploy-backend deploy-frontend teardown teardown-frontend teardown-backend teardown-queue

# === DEPLOY (deployment order: queue → backend → frontend) ===

deploy: deploy-queue deploy-backend deploy-frontend

deploy-queue:
	$(eval REPO_URI := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr \
		--query 'Stacks[0].Outputs[?OutputKey==`RepositoryUri`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-queue \
		--template-file infra/cfn/queue/queue.yml \
		--capabilities CAPABILITY_NAMED_IAM \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
			ImageUri=$(REPO_URI):$(IMAGE_TAG) \
			AuthIssuer=$(OIDC_ISSUER) AuthAudience=$(OIDC_CLIENT_ID) \
			FunctionName=fn-worker \
			ImageCommand=python,-m,sqs_handler \
			EnableJobsTable=true \
		--no-fail-on-empty-changeset

deploy-backend: deploy-queue
	$(eval REPO_URI := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr \
		--query 'Stacks[0].Outputs[?OutputKey==`RepositoryUri`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval QUEUE_URL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-queue \
		--query 'Stacks[0].Outputs[?OutputKey==`QueueUrl`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval QUEUE_ARN := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-queue \
		--query 'Stacks[0].Outputs[?OutputKey==`QueueArn`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-backend \
		--template-file infra/cfn/backend/backend.yml \
		--capabilities CAPABILITY_NAMED_IAM \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
			ImageUri=$(REPO_URI):$(IMAGE_TAG) \
			AuthIssuer=$(OIDC_ISSUER) AuthAudience=$(OIDC_CLIENT_ID) \
			FunctionName=fn InvokeMode=RESPONSE_STREAM Timeout=300 \
			EnablePassengersTable=true \
			EnableSqsIntegration=true \
			SqsQueueUrl=$(QUEUE_URL) \
			SqsSendQueueArns=$(QUEUE_ARN) \
		--no-fail-on-empty-changeset

deploy-frontend:
	$(eval LOG_BUCKET_NAME := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-security \
		--query 'Stacks[0].Outputs[?OutputKey==`LogBucketName`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-frontend \
		--template-file infra/cfn/frontend/frontend.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
			LogBucketDomainName=$(LOG_BUCKET_NAME).s3.amazonaws.com \
		--no-fail-on-empty-changeset

# === TEARDOWN (reverse order: frontend → backend → queue) ===

teardown: teardown-frontend teardown-backend teardown-queue

teardown-frontend:
	aws cloudformation delete-stack \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-frontend
	aws cloudformation wait stack-delete-complete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-frontend

teardown-backend:
	aws cloudformation delete-stack \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-backend
	aws cloudformation wait stack-delete-complete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-backend

teardown-queue:
	aws cloudformation delete-stack \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-queue
	aws cloudformation wait stack-delete-complete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-queue
