# Deploy targets for react-rest-lambda pattern
# Generated by /ipa.compose — do not edit manually
#
# Usage:
#   make -f scripts/deploy.mk deploy        # Deploy all stacks
#   make -f scripts/deploy.mk deploy-fn     # Deploy single stack
#   make -f scripts/deploy.mk teardown      # Delete all stacks (reverse order)
#
# Variable resolution:
#   Local:  -include .env loads values from file
#   CI/CD:  -include silently skips; Make inherits env vars from CodeBuild

-include .env
export

# Resolve version from app-lib/pyproject.toml + git SHA
IMAGE_TAG := $(shell python3 scripts/util/version.py docker)

# Derive account hash for globally-unique identifiers (e.g., Cognito domain prefix)
APP_ACCOUNT_HASH := $(shell echo -n "$(AWS_ACCOUNT_ID)" | shasum | cut -c1-8)

.PHONY: deploy deploy-ddb-passengers deploy-fn deploy-apigwv2 deploy-s3 deploy-cf teardown teardown-cf teardown-s3 teardown-apigwv2 teardown-fn teardown-ddb-passengers

# === DEPLOY (deployment order) ===

deploy: deploy-ddb-passengers deploy-fn deploy-apigwv2 deploy-s3 deploy-cf

deploy-ddb-passengers:
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ddb-passengers \
		--template-file infra/cfn/dynamodb/dynamodb.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
			TableName=passengers \
		--no-fail-on-empty-changeset

deploy-fn: deploy-ddb-passengers
	$(eval REPOSITORY_URI := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr \
		--query 'Stacks[0].Outputs[?OutputKey==`RepositoryUri`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval TABLE_ARN := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ddb-passengers \
		--query 'Stacks[0].Outputs[?OutputKey==`TableArn`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval ISSUER_URL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`IssuerUrl`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval USER_POOL_CLIENT_ID := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval LOG_BUCKET_NAME := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-security \
		--query 'Stacks[0].Outputs[?OutputKey==`LogBucketName`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-fn \
		--template-file infra/cfn/lambda/lambda.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
			FunctionName=fn InvokeMode=RESPONSE_STREAM Timeout=300 \
			ImageUri=$(REPOSITORY_URI):$(IMAGE_TAG) \
			AuthIssuer=$(ISSUER_URL) AuthAudience=$(USER_POOL_CLIENT_ID) \
			DynamoDbTableArns=$(TABLE_ARN) \
			LogBucketName=$(LOG_BUCKET_NAME) \
		--capabilities CAPABILITY_NAMED_IAM \
		--no-fail-on-empty-changeset

deploy-apigwv2: deploy-fn
	$(eval FUNCTION_ARN := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-fn \
		--query 'Stacks[0].Outputs[?OutputKey==`FunctionArn`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval ISSUER_URL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`IssuerUrl`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval USER_POOL_CLIENT_ID := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-apigwv2 \
		--template-file infra/cfn/apigateway-v2/apigateway-v2.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
			ApiName=$(APP_NAMESPACE)-$(APP_ENV)-api \
			LambdaFunctionArn=$(FUNCTION_ARN) \
			IssuerUrl=$(ISSUER_URL) UserPoolClientId=$(USER_POOL_CLIENT_ID) \
		--no-fail-on-empty-changeset

deploy-s3:
	$(eval LOG_BUCKET_NAME := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-security \
		--query 'Stacks[0].Outputs[?OutputKey==`LogBucketName`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-s3 \
		--template-file infra/cfn/s3/s3.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
			LogBucketName=$(LOG_BUCKET_NAME) \
		--no-fail-on-empty-changeset

deploy-cf: deploy-s3
	$(eval S3_BUCKET_DOMAIN_NAME := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-s3 \
		--query 'Stacks[0].Outputs[?OutputKey==`BucketDomainName`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval S3_BUCKET_ARN := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-s3 \
		--query 'Stacks[0].Outputs[?OutputKey==`BucketArn`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval S3_BUCKET_NAME := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-s3 \
		--query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval LOG_BUCKET_NAME := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-security \
		--query 'Stacks[0].Outputs[?OutputKey==`LogBucketName`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cf \
		--template-file infra/cfn/cloudfront/cloudfront.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
			S3BucketDomainName=$(S3_BUCKET_DOMAIN_NAME) \
			S3BucketArn=$(S3_BUCKET_ARN) \
			S3BucketName=$(S3_BUCKET_NAME) \
			LogBucketDomainName=$(LOG_BUCKET_NAME).s3.amazonaws.com \
		--no-fail-on-empty-changeset

# === TEARDOWN (reverse order) ===

teardown: teardown-cf teardown-s3 teardown-apigwv2 teardown-fn teardown-ddb-passengers

teardown-cf:
	aws cloudformation delete-stack \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cf
	aws cloudformation wait stack-delete-complete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cf

teardown-s3:
	aws cloudformation delete-stack \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-s3
	aws cloudformation wait stack-delete-complete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-s3

teardown-apigwv2:
	aws cloudformation delete-stack \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-apigwv2
	aws cloudformation wait stack-delete-complete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-apigwv2

teardown-fn:
	aws cloudformation delete-stack \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-fn
	aws cloudformation wait stack-delete-complete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-fn

teardown-ddb-passengers:
	aws cloudformation delete-stack \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ddb-passengers
	aws cloudformation wait stack-delete-complete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ddb-passengers
