# Deploy targets for react-rest-lambda pattern
# Generated by /ipa.compose — do not edit manually
#
# Usage:
#   make -f scripts/deploy.mk deploy           # Deploy all stacks
#   make -f scripts/deploy.mk deploy-cognito   # Deploy single stack
#   make -f scripts/deploy.mk teardown         # Delete all stacks (reverse order)
#
# Variable resolution:
#   Local:  -include .env loads values from file
#   CI/CD:  -include silently skips; Make inherits env vars from CodeBuild

-include .env

.PHONY: deploy deploy-cognito teardown teardown-cognito

deploy: deploy-cognito

deploy-cognito:
	uv run --project utils deploy cfn \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--template infra/cfn/cognito/cognito.yml \
		--parameter-overrides "Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) CognitoDomainPrefix=$(APP_COGNITO_DOMAIN_PREFIX)"

# === TEARDOWN (reverse order) ===

teardown: teardown-cognito

teardown-cognito:
	uv run --project utils deploy cfn-delete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito
