# Environment variable sync — writes Terraform outputs to .env
# Generated by /ipa-compose — do not edit manually
#
# This is the canonical bridge between live stack outputs and the Make system.
# deploy.mk and post-deploy.mk read values from .env rather than calling
# describe-stacks or terraform output directly. CodeBuild stages invoke this
# as a prelude before their main target.
#
# Usage:
#   make -f scripts/env.mk update-env                  # Sync all stack outputs
#   make -f scripts/env.mk update-env-{stack-suffix}   # Sync one stack only

-include .env

AWS_CREDS := $(if $(AWS_PROFILE),AWS_PROFILE=$(AWS_PROFILE),) $(if $(AWS_REGION),AWS_REGION=$(AWS_REGION),)

TF_BACKEND_CONFIG := \
  -backend-config="bucket=$(TF_STATE_BUCKET)" \
  -backend-config="region=$(AWS_REGION)" \
  -backend-config="use_lockfile=true"

.PHONY: update-env update-env-tfstate update-env-cognito update-env-ecr update-env-backend update-env-frontend update-env-sqs update-env-pipeline

update-env: update-env-tfstate update-env-cognito update-env-ecr update-env-backend update-env-frontend update-env-sqs update-env-pipeline

update-env-tfstate:
	$(eval TF_STATE_BUCKET_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-tfstate \
		--query 'Stacks[0].Outputs[?OutputKey==`StateBucketName`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval TF_STATE_LOCK_TABLE_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-tfstate \
		--query 'Stacks[0].Outputs[?OutputKey==`LockTableName`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	@grep -v '^TF_STATE_BUCKET=\|^TF_STATE_LOCK_TABLE=\|^# Terraform State Configuration' .env > .env.tmp 2>/dev/null; mv .env.tmp .env || true
	@echo "" >> .env
	@echo "# Terraform State Configuration (written by env.mk after tfstate deploy)" >> .env
	@echo "TF_STATE_BUCKET=$(TF_STATE_BUCKET_VAL)" >> .env
	@echo "TF_STATE_LOCK_TABLE=$(TF_STATE_LOCK_TABLE_VAL)" >> .env

update-env-cognito:
	$(eval OIDC_ISSUER_VAL := $(shell cd infra/tf/cognito && \
		( $(AWS_CREDS) terraform init -input=false -reconfigure \
			$(TF_BACKEND_CONFIG) \
			-backend-config="key=$(APP_NAMESPACE)-$(APP_ENV)/cognito/terraform.tfstate" > /dev/null 2>&1 \
		  && $(AWS_CREDS) terraform output -raw issuer_url 2>/dev/null ) \
		|| true))
	$(eval OIDC_CLIENT_ID_VAL := $(shell cd infra/tf/cognito && \
		$(AWS_CREDS) terraform output -raw user_pool_client_id 2>/dev/null || true))
	$(eval OIDC_END_SESSION_VAL := $(shell cd infra/tf/cognito && \
		$(AWS_CREDS) terraform output -raw end_session_endpoint 2>/dev/null || true))
	$(eval OIDC_USER_POOL_ID_VAL := $(shell cd infra/tf/cognito && \
		$(AWS_CREDS) terraform output -raw user_pool_id 2>/dev/null || true))
	$(eval COGNITO_DOMAIN_PREFIX_VAL := $(shell cd infra/tf/cognito && \
		$(AWS_CREDS) terraform output -raw cognito_domain 2>/dev/null || true))
	@if [ -z "$(OIDC_ISSUER_VAL)" ] && [ -z "$$IPA_ALLOW_EMPTY_OUTPUTS" ]; then \
		if ! command -v terraform > /dev/null; then \
			echo "ERROR: terraform binary not found — install via buildspec install phase"; exit 1; \
		fi; \
		echo "WARN: cognito outputs are empty (stack not yet deployed?). Continuing."; \
	fi
	@grep -v '^OIDC_\|^COGNITO_DOMAIN_PREFIX=\|^# OIDC Configuration' .env > .env.tmp 2>/dev/null; mv .env.tmp .env || true
	@echo "" >> .env
	@echo "# OIDC Configuration (written by env.mk after cognito deploy)" >> .env
	@echo "OIDC_ISSUER=$(OIDC_ISSUER_VAL)" >> .env
	@echo "OIDC_CLIENT_ID=$(OIDC_CLIENT_ID_VAL)" >> .env
	@echo "OIDC_END_SESSION_ENDPOINT=$(OIDC_END_SESSION_VAL)" >> .env
	@echo "OIDC_USER_POOL_ID=$(OIDC_USER_POOL_ID_VAL)" >> .env
	@echo "COGNITO_DOMAIN_PREFIX=$(COGNITO_DOMAIN_PREFIX_VAL)" >> .env

update-env-ecr:
	$(eval ECR_REPO_URI_VAL := $(shell cd infra/tf/ecr && \
		( $(AWS_CREDS) terraform init -input=false -reconfigure \
			$(TF_BACKEND_CONFIG) \
			-backend-config="key=$(APP_NAMESPACE)-$(APP_ENV)/ecr/terraform.tfstate" > /dev/null 2>&1 \
		  && $(AWS_CREDS) terraform output -raw repository_uri 2>/dev/null ) \
		|| true))
	@if [ -z "$(ECR_REPO_URI_VAL)" ] && [ -z "$$IPA_ALLOW_EMPTY_OUTPUTS" ]; then \
		if ! command -v terraform > /dev/null; then \
			echo "ERROR: terraform binary not found — install via buildspec install phase"; exit 1; \
		fi; \
		echo "WARN: ECR repository_uri output is empty (stack not yet deployed?). Continuing."; \
	fi
	@grep -v '^ECR_REPO_URI\|^# ECR Configuration' .env > .env.tmp 2>/dev/null; mv .env.tmp .env || true
	@echo "" >> .env
	@echo "# ECR Configuration (written by env.mk after ecr deploy)" >> .env
	@echo "ECR_REPO_URI=$(ECR_REPO_URI_VAL)" >> .env

update-env-backend:
	$(eval API_URL_VAL := $(shell cd infra/tf/backend && \
		( $(AWS_CREDS) terraform init -input=false -reconfigure \
			$(TF_BACKEND_CONFIG) \
			-backend-config="key=$(APP_NAMESPACE)-$(APP_ENV)/backend/terraform.tfstate" > /dev/null 2>&1 \
		  && $(AWS_CREDS) terraform output -raw api_url 2>/dev/null ) \
		|| true))
	$(eval FUNCTION_NAME_VAL := $(shell cd infra/tf/backend && \
		$(AWS_CREDS) terraform output -raw function_name 2>/dev/null || true))
	@if [ -z "$(API_URL_VAL)" ] && [ -z "$$IPA_ALLOW_EMPTY_OUTPUTS" ]; then \
		if ! command -v terraform > /dev/null; then \
			echo "ERROR: terraform binary not found — install via buildspec install phase"; exit 1; \
		fi; \
		echo "WARN: backend outputs are empty (stack not yet deployed?). Continuing."; \
	fi
	@grep -v '^API_URL=\|^FUNCTION_NAME=\|^# Backend Configuration' .env > .env.tmp 2>/dev/null; mv .env.tmp .env || true
	@echo "" >> .env
	@echo "# Backend Configuration (written by env.mk after backend deploy)" >> .env
	@echo "API_URL=$(API_URL_VAL)" >> .env
	@echo "FUNCTION_NAME=$(FUNCTION_NAME_VAL)" >> .env

update-env-frontend:
	$(eval APP_URL_VAL := $(shell cd infra/tf/frontend && \
		( $(AWS_CREDS) terraform init -input=false -reconfigure \
			$(TF_BACKEND_CONFIG) \
			-backend-config="key=$(APP_NAMESPACE)-$(APP_ENV)/frontend/terraform.tfstate" > /dev/null 2>&1 \
		  && $(AWS_CREDS) terraform output -raw app_url 2>/dev/null ) \
		|| true))
	$(eval BUCKET_NAME_VAL := $(shell cd infra/tf/frontend && \
		$(AWS_CREDS) terraform output -raw bucket_name 2>/dev/null || true))
	$(eval DISTRIBUTION_ID_VAL := $(shell cd infra/tf/frontend && \
		$(AWS_CREDS) terraform output -raw distribution_id 2>/dev/null || true))
	@if [ -z "$(APP_URL_VAL)" ] && [ -z "$$IPA_ALLOW_EMPTY_OUTPUTS" ]; then \
		if ! command -v terraform > /dev/null; then \
			echo "ERROR: terraform binary not found — install via buildspec install phase"; exit 1; \
		fi; \
		echo "WARN: frontend outputs are empty (stack not yet deployed?). Continuing."; \
	fi
	@grep -v '^APP_URL=\|^BUCKET_NAME=\|^DISTRIBUTION_ID=\|^# Frontend Configuration' .env > .env.tmp 2>/dev/null; mv .env.tmp .env || true
	@echo "" >> .env
	@echo "# Frontend Configuration (written by env.mk after frontend deploy)" >> .env
	@echo "APP_URL=$(APP_URL_VAL)" >> .env
	@echo "BUCKET_NAME=$(BUCKET_NAME_VAL)" >> .env
	@echo "DISTRIBUTION_ID=$(DISTRIBUTION_ID_VAL)" >> .env

update-env-sqs:
	$(eval SQS_QUEUE_URL_VAL := $(shell cd infra/tf/queue && \
		( $(AWS_CREDS) terraform init -input=false -reconfigure \
			$(TF_BACKEND_CONFIG) \
			-backend-config="key=$(APP_NAMESPACE)-$(APP_ENV)/queue/terraform.tfstate" > /dev/null 2>&1 \
		  && $(AWS_CREDS) terraform output -raw queue_url 2>/dev/null ) \
		|| true))
	$(eval SQS_QUEUE_ARN_VAL := $(shell cd infra/tf/queue && \
		$(AWS_CREDS) terraform output -raw queue_arn 2>/dev/null || true))
	@if [ -z "$(SQS_QUEUE_URL_VAL)" ] && [ -z "$$IPA_ALLOW_EMPTY_OUTPUTS" ]; then \
		if ! command -v terraform > /dev/null; then \
			echo "ERROR: terraform binary not found — install via buildspec install phase"; exit 1; \
		fi; \
		echo "WARN: SQS outputs are empty (stack not yet deployed?). Continuing."; \
	fi
	@grep -v '^SQS_QUEUE_URL=\|^SQS_QUEUE_ARN=\|^# SQS Configuration' .env > .env.tmp 2>/dev/null; mv .env.tmp .env || true
	@echo "" >> .env
	@echo "# SQS Configuration (written by env.mk after queue deploy)" >> .env
	@echo "SQS_QUEUE_URL=$(SQS_QUEUE_URL_VAL)" >> .env
	@echo "SQS_QUEUE_ARN=$(SQS_QUEUE_ARN_VAL)" >> .env

update-env-pipeline:
	$(eval PIPELINE_NAME_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-codepipeline \
		--query 'Stacks[0].Outputs[?OutputKey==`PipelineName`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval CODEBUILD_PROJECT_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-codepipeline \
		--query 'Stacks[0].Outputs[?OutputKey==`CodeBuildProjectName`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval CODECOMMIT_REPO_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-codecommit \
		--query 'Stacks[0].Outputs[?OutputKey==`RepositoryName`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval CODECOMMIT_CLONE_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-codecommit \
		--query 'Stacks[0].Outputs[?OutputKey==`CloneUrlHttp`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	@grep -v '^PIPELINE_STACK_NAME=\|^PIPELINE_NAME=\|^CODEBUILD_PROJECT_NAME=\|^CODECOMMIT_STACK_NAME=\|^CODECOMMIT_REPO_NAME=\|^CODECOMMIT_CLONE_URL=\|^# Pipeline Configuration' .env > .env.tmp 2>/dev/null; mv .env.tmp .env || true
	@echo "" >> .env
	@echo "# Pipeline Configuration (written by env.mk after codepipeline deploy)" >> .env
	@echo "PIPELINE_STACK_NAME=$(APP_NAMESPACE)-$(APP_ENV)-codepipeline" >> .env
	@echo "PIPELINE_NAME=$(PIPELINE_NAME_VAL)" >> .env
	@echo "CODEBUILD_PROJECT_NAME=$(CODEBUILD_PROJECT_VAL)" >> .env
	@echo "CODECOMMIT_STACK_NAME=$(APP_NAMESPACE)-$(APP_ENV)-codecommit" >> .env
	@echo "CODECOMMIT_REPO_NAME=$(CODECOMMIT_REPO_VAL)" >> .env
	@echo "CODECOMMIT_CLONE_URL=$(CODECOMMIT_CLONE_VAL)" >> .env
