# Environment variable sync — writes stack outputs to .env
# Generated by /ipa.compose — do not edit manually
#
# Syncs deployed stack outputs to .env so the local dev server
# can read them via load_dotenv(). Skipped in CI/CD (no .env file).
#
# Usage:
#   make -f scripts/env.mk update-env           # Sync all stack outputs
#   make -f scripts/env.mk update-env-cognito   # Sync cognito only
#   make -f scripts/env.mk update-env-ecr       # Sync ecr only
#   make -f scripts/env.mk update-env-sqs       # Sync sqs only

-include .env

.PHONY: update-env update-env-cognito update-env-ecr update-env-sqs

update-env: update-env-cognito update-env-ecr update-env-sqs

update-env-cognito:
	$(eval OIDC_ISSUER_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`IssuerUrl`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval OIDC_CLIENT_ID_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval OIDC_DISCOVERY_URL_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`DiscoveryUrl`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval OIDC_END_SESSION_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`EndSessionEndpoint`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval OIDC_USER_POOL_ID_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	@echo "Writing OIDC configuration to .env..."
	@grep -v '^OIDC_\|^# OIDC Configuration' .env > .env.tmp 2>/dev/null; mv .env.tmp .env || true
	@echo "" >> .env
	@echo "# OIDC Configuration (written by /ipa.deploy after cognito deploy)" >> .env
	@echo "OIDC_ISSUER=$(OIDC_ISSUER_VAL)" >> .env
	@echo "OIDC_CLIENT_ID=$(OIDC_CLIENT_ID_VAL)" >> .env
	@echo "OIDC_DISCOVERY_URL=$(OIDC_DISCOVERY_URL_VAL)" >> .env
	@echo "OIDC_END_SESSION_ENDPOINT=$(OIDC_END_SESSION_VAL)" >> .env
	@echo "OIDC_USER_POOL_ID=$(OIDC_USER_POOL_ID_VAL)" >> .env

update-env-ecr:
	$(eval ECR_REPO_URI_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr \
		--query 'Stacks[0].Outputs[?OutputKey==`RepositoryUri`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	@echo "Writing ECR configuration to .env..."
	@grep -v '^ECR_REPO_URI\|^# ECR Configuration' .env > .env.tmp 2>/dev/null; mv .env.tmp .env || true
	@echo "" >> .env
	@echo "# ECR Configuration (written by /ipa.deploy after ecr deploy)" >> .env
	@echo "ECR_REPO_URI=$(ECR_REPO_URI_VAL)" >> .env

update-env-sqs:
	$(eval SQS_QUEUE_URL_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-queue \
		--query 'Stacks[0].Outputs[?OutputKey==`QueueUrl`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	@echo "Writing SQS configuration to .env..."
	@grep -v '^SQS_QUEUE_URL\|^# SQS Configuration' .env > .env.tmp 2>/dev/null; mv .env.tmp .env || true
	@echo "" >> .env
	@echo "# SQS Configuration (written by /ipa.deploy after queue deploy)" >> .env
	@echo "SQS_QUEUE_URL=$(SQS_QUEUE_URL_VAL)" >> .env
