# Post-deploy targets for react-rest-lambda pattern
# Generated by /ipa.compose — do not edit manually
#
# Runs automatically after a successful deploy via /ipa.deploy.
# Can also be run independently: make -f scripts/post-deploy.mk post-deploy
#
# Variable resolution:
#   Local:  -include .env loads values from file
#   CI/CD:  -include silently skips; Make inherits env vars from CodeBuild

-include .env
export

# Derive account hash for globally-unique identifiers (e.g., Cognito domain prefix)
APP_ACCOUNT_HASH := $(shell echo -n "$(AWS_ACCOUNT_ID)" | shasum | cut -c1-8)

.PHONY: post-deploy load-data configure-frontend upload-frontend invalidate-cf update-cognito-callback update-apigwv2-cors

post-deploy: load-data configure-frontend upload-frontend invalidate-cf update-cognito-callback update-apigwv2-cors

load-data:
	cd app-lib && uv run python -m app_lib.features.passengers.util.load_dynamodb_util

configure-frontend:
	$(eval API_URL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-apigwv2 \
		--query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval APP_URL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cf \
		--query 'Stacks[0].Outputs[?OutputKey==`AppUrl`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	python3 scripts/util/configure_frontend.py \
		--api-base-url "$(API_URL)" \
		--oidc-authority "$(OIDC_ISSUER)" \
		--oidc-client-id "$(OIDC_CLIENT_ID)" \
		--oidc-redirect-uri "$(APP_URL)/authentication/callback" \
		--oidc-end-session-endpoint "$(OIDC_END_SESSION_ENDPOINT)" \
		--output web-client/dist/config.js

upload-frontend: configure-frontend
	$(eval BUCKET_NAME := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-s3 \
		--query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	aws s3 sync web-client/dist/ s3://$(BUCKET_NAME)/ --delete

invalidate-cf: upload-frontend
	$(eval DISTRIBUTION_ID := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cf \
		--query 'Stacks[0].Outputs[?OutputKey==`DistributionId`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval INVALIDATION_ID := $(shell aws cloudfront create-invalidation \
		--distribution-id $(DISTRIBUTION_ID) \
		--paths "/*" \
		--query 'Invalidation.Id' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	aws cloudfront wait invalidation-completed \
		--distribution-id $(DISTRIBUTION_ID) \
		--id $(INVALIDATION_ID)

update-cognito-callback: invalidate-cf
	$(eval APP_URL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cf \
		--query 'Stacks[0].Outputs[?OutputKey==`AppUrl`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--template-file infra/cfn/cognito/cognito.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
			CognitoDomainPrefix=$(APP_NAMESPACE)-$(APP_ENV)-$(APP_ACCOUNT_HASH) \
			CallbackURL=$(APP_URL)/authentication/callback \
		--no-fail-on-empty-changeset

update-apigwv2-cors: update-cognito-callback
	$(eval APP_URL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cf \
		--query 'Stacks[0].Outputs[?OutputKey==`AppUrl`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval FUNCTION_ARN := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-fn \
		--query 'Stacks[0].Outputs[?OutputKey==`FunctionArn`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-apigwv2 \
		--template-file infra/cfn/apigateway-v2/apigateway-v2.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
			ApiName=$(APP_NAMESPACE)-$(APP_ENV)-api \
			LambdaFunctionArn=$(FUNCTION_ARN) \
			IssuerUrl=$(OIDC_ISSUER) UserPoolClientId=$(OIDC_CLIENT_ID) \
			AllowedOrigin=$(APP_URL) \
		--no-fail-on-empty-changeset
