# Post-deploy targets for react-rest-lambda pattern
# Generated by /ipa.compose — do not edit manually
#
# Runs automatically after a successful deploy via /ipa.deploy.
# Can also be run independently: make -f scripts/post-deploy.mk post-deploy
#
# Variable resolution:
#   Local:  -include .env loads values from file
#   CI/CD:  -include silently skips; Make inherits env vars from CodeBuild

-include .env

.PHONY: post-deploy configure-frontend upload-frontend invalidate-cf update-cognito-callback

post-deploy: configure-frontend upload-frontend invalidate-cf update-cognito-callback

configure-frontend:
	$(eval API_URL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-apigw \
		--query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' \
		--output text))
	$(eval APP_URL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cf \
		--query 'Stacks[0].Outputs[?OutputKey==`AppUrl`].OutputValue' \
		--output text))
	$(eval ISSUER_URL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`IssuerUrl`].OutputValue' \
		--output text))
	$(eval CLIENT_ID := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' \
		--output text))
	$(eval END_SESSION := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`EndSessionEndpoint`].OutputValue' \
		--output text))
	python3 scripts/util/configure_frontend.py \
		--api-base-url "$(API_URL)" \
		--oidc-authority "$(ISSUER_URL)" \
		--oidc-client-id "$(CLIENT_ID)" \
		--oidc-redirect-uri "$(APP_URL)/authentication/callback" \
		--oidc-end-session-endpoint "$(END_SESSION)" \
		--output web-client/dist/config.js

upload-frontend: configure-frontend
	$(eval BUCKET_NAME := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-s3 \
		--query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' \
		--output text))
	aws s3 sync web-client/dist/ s3://$(BUCKET_NAME)/ --delete

invalidate-cf: upload-frontend
	$(eval DISTRIBUTION_ID := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cf \
		--query 'Stacks[0].Outputs[?OutputKey==`DistributionId`].OutputValue' \
		--output text))
	$(eval INVALIDATION_ID := $(shell aws cloudfront create-invalidation \
		--distribution-id $(DISTRIBUTION_ID) \
		--paths "/*" \
		--query 'Invalidation.Id' \
		--output text))
	aws cloudfront wait invalidation-completed \
		--distribution-id $(DISTRIBUTION_ID) \
		--id $(INVALIDATION_ID)

update-cognito-callback: invalidate-cf
	$(eval APP_URL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cf \
		--query 'Stacks[0].Outputs[?OutputKey==`AppUrl`].OutputValue' \
		--output text))
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--template-file infra/cfn/cognito/cognito.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) CognitoDomainPrefix=$(APP_NAMESPACE)-$(APP_ENV)-369530 CallbackURL=$(APP_URL)/authentication/callback \
		--no-fail-on-empty-changeset
