# Prepare targets — one-time infrastructure prerequisites
# Generated by /ipa.compose — do not edit manually
#
# These stacks must exist before build and deploy scripts can run.
# Run once after /ipa.security and /ipa.compose, re-run when prepare targets change.
#
# Usage:
#   make -f scripts/prepare.mk prepare           # Deploy all prepare stacks
#   make -f scripts/prepare.mk prepare-cognito   # Deploy single prepare stack
#   make -f scripts/prepare.mk teardown-prepare   # Delete all prepare stacks (manual only)
#
# Variable resolution:
#   Local:  -include .env loads values from file
#   CI/CD:  Not applicable — prepare runs locally before pipeline setup

-include .env

# Derive account hash for globally-unique identifiers (e.g., Cognito domain prefix)
APP_ACCOUNT_HASH := $(shell echo -n "$(AWS_ACCOUNT_ID)" | shasum | cut -c1-8)

.PHONY: prepare prepare-cognito prepare-cognito-env prepare-ecr prepare-ecr-env teardown-prepare teardown-ecr teardown-cognito

prepare: prepare-cognito prepare-cognito-env prepare-ecr prepare-ecr-env

prepare-cognito:
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--template-file infra/cfn/cognito/cognito.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
			CognitoDomainPrefix=$(APP_NAMESPACE)-$(APP_ENV)-$(APP_ACCOUNT_HASH) \
		--no-fail-on-empty-changeset

prepare-cognito-env: prepare-cognito
	$(eval OIDC_ISSUER_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`IssuerUrl`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval OIDC_CLIENT_ID_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval OIDC_DISCOVERY_URL_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`DiscoveryUrl`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval OIDC_END_SESSION_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`EndSessionEndpoint`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	$(eval OIDC_USER_POOL_ID_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	@echo "Writing OIDC configuration to .env..."
	@grep -v '^OIDC_\|^# OIDC Configuration' .env > .env.tmp 2>/dev/null; mv .env.tmp .env || true
	@echo "" >> .env
	@echo "# OIDC Configuration (written by /ipa.prepare after cognito deploy)" >> .env
	@echo "OIDC_ISSUER=$(OIDC_ISSUER_VAL)" >> .env
	@echo "OIDC_CLIENT_ID=$(OIDC_CLIENT_ID_VAL)" >> .env
	@echo "OIDC_DISCOVERY_URL=$(OIDC_DISCOVERY_URL_VAL)" >> .env
	@echo "OIDC_END_SESSION_ENDPOINT=$(OIDC_END_SESSION_VAL)" >> .env
	@echo "OIDC_USER_POOL_ID=$(OIDC_USER_POOL_ID_VAL)" >> .env

prepare-ecr: prepare-cognito-env
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr \
		--template-file infra/cfn/ecr/ecr.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
		--no-fail-on-empty-changeset

prepare-ecr-env: prepare-ecr
	$(eval ECR_REPO_URI_VAL := $(shell aws cloudformation describe-stacks \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr \
		--query 'Stacks[0].Outputs[?OutputKey==`RepositoryUri`].OutputValue' \
		--output text \
		$(if $(AWS_PROFILE),--profile $(AWS_PROFILE),) $(if $(AWS_REGION),--region $(AWS_REGION),)))
	@echo "Writing ECR configuration to .env..."
	@grep -v '^ECR_REPO_URI\|^# ECR Configuration' .env > .env.tmp 2>/dev/null; mv .env.tmp .env || true
	@echo "" >> .env
	@echo "# ECR Configuration (written by /ipa.prepare after ecr deploy)" >> .env
	@echo "ECR_REPO_URI=$(ECR_REPO_URI_VAL)" >> .env

# === TEARDOWN (manual only — never auto-deleted by /ipa.destroy) ===

teardown-prepare: teardown-ecr teardown-cognito

teardown-ecr:
	aws cloudformation delete-stack \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr
	aws cloudformation wait stack-delete-complete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr

teardown-cognito:
	aws cloudformation delete-stack \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito
	aws cloudformation wait stack-delete-complete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito
