# Prepare targets — one-time infrastructure prerequisites
# Generated by /ipa.compose — do not edit manually
#
# These stacks must exist before build and deploy scripts can run.
# Run once after /ipa.security and /ipa.compose, re-run when prepare targets change.
#
# Usage:
#   make -f scripts/prepare.mk prepare           # Deploy all prepare stacks
#   make -f scripts/prepare.mk prepare-ecr       # Deploy single prepare stack
#   make -f scripts/prepare.mk teardown-prepare  # Delete all prepare stacks (manual only)
#
# Variable resolution:
#   Local:  -include .env loads values from file
#   CI/CD:  Not applicable — prepare runs locally before pipeline setup

-include .env

.PHONY: prepare prepare-ecr teardown-prepare teardown-ecr

prepare: prepare-ecr

prepare-ecr:
	uv run --project utils deploy cfn \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr \
		--template infra/cfn/ecr/ecr.yml \
		--parameter-overrides "Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV)"

# === TEARDOWN (manual only — never auto-deleted by /ipa.destroy) ===

teardown-prepare: teardown-ecr

teardown-ecr:
	uv run --project utils deploy cfn-delete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr
