# Prepare targets — one-time infrastructure prerequisites
# Generated by /ipa.compose — do not edit manually
#
# These stacks must exist before build and deploy scripts can run.
# Run once after /ipa.security and /ipa.compose, re-run when prepare targets change.
#
# Usage:
#   make -f scripts/prepare.mk prepare           # Deploy all prepare stacks
#   make -f scripts/prepare.mk prepare-cognito   # Deploy single prepare stack
#   make -f scripts/prepare.mk teardown-prepare   # Delete all prepare stacks (manual only)
#
# Variable resolution:
#   Local:  -include .env loads values from file
#   CI/CD:  Not applicable — prepare runs locally before pipeline setup

-include .env

# Derive account hash for globally-unique identifiers (e.g., Cognito domain prefix)
APP_ACCOUNT_HASH := $(shell printf '%s' "$(AWS_ACCOUNT_ID)" | shasum | cut -c1-8)

.PHONY: prepare prepare-cognito prepare-ecr teardown-prepare teardown-ecr teardown-cognito

prepare: prepare-cognito prepare-ecr

prepare-cognito:
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito \
		--template-file infra/cfn/cognito/cognito.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
			CognitoDomainPrefix=$(APP_NAMESPACE)-$(APP_ENV)-$(APP_ACCOUNT_HASH) \
		--no-fail-on-empty-changeset

prepare-ecr: prepare-cognito
	aws cloudformation deploy \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr \
		--template-file infra/cfn/ecr/ecr.yml \
		--parameter-overrides Namespace=$(APP_NAMESPACE) Environment=$(APP_ENV) \
		--no-fail-on-empty-changeset

# === TEARDOWN (manual only — never auto-deleted by /ipa.destroy) ===

teardown-prepare: teardown-ecr teardown-cognito

teardown-ecr:
	aws cloudformation delete-stack \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr
	aws cloudformation wait stack-delete-complete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-ecr

teardown-cognito:
	aws cloudformation delete-stack \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito
	aws cloudformation wait stack-delete-complete \
		--stack-name $(APP_NAMESPACE)-$(APP_ENV)-cognito
