# Test targets for frontend + backend + queue composition
# Generated by /ipa.compose — do not edit manually
#
# Usage:
#   make -f scripts/test.mk test

-include .env

.PHONY: test

test:
	@echo "No tests configured"
