# Test targets for react-rest-lambda pattern
# Generated by /ipa.compose — do not edit manually
#
# Usage:
#   make -f scripts/test.mk test          # Run all tests
#   make -f scripts/test.mk test-unit     # Unit tests only
#   make -f scripts/test.mk test-security # Security scans only
#   make -f scripts/test.mk test-cfn-lint # CFN template validation

-include .env

.PHONY: test test-unit test-security test-cfn-lint

test: test-unit test-security test-cfn-lint

test-unit:
	uv run --project utils test unit

test-security:
	uv run --project utils test security

test-cfn-lint:
	uv run --project utils test cfn-lint --template infra/cfn/ecr/ecr.yml
