# Test targets for react-rest-lambda + sqs-lambda pattern
# Generated by /ipa.compose — do not edit manually
#
# Usage:
#   make -f scripts/test.mk test

-include .env

.PHONY: test

test:
	@echo "No tests configured"
