import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {existsSync} from 'fs';
import {resolve} from 'path';

const showWorking = existsSync(resolve(__dirname, 'docs/working'));

const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [{type: 'autogenerated', dirName: 'getting-started'}],
  patternsSidebar: [{type: 'autogenerated', dirName: 'patterns'}],
  guidesSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  userDocsSidebar: [{type: 'autogenerated', dirName: 'user-docs'}],
  developerDocsSidebar: [{type: 'autogenerated', dirName: 'developer-docs'}],
  ...(showWorking ? {
    workingSidebar: [{type: 'autogenerated', dirName: 'working'}],
  } : {}),
};

export default sidebars;
