// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {existsSync} from 'fs';
import {resolve} from 'path';

const showWorking = existsSync(resolve(__dirname, 'docs/working'));
const showUserDocs = existsSync(resolve(__dirname, 'docs/user-docs'));

const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [{type: 'autogenerated', dirName: 'getting-started'}],
  stacksSidebar: [{type: 'autogenerated', dirName: 'stacks'}],
  guidesSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  developerDocsSidebar: [{type: 'autogenerated', dirName: 'developer-docs'}],
  ...(showUserDocs ? {
    userDocsSidebar: [{type: 'autogenerated', dirName: 'user-docs'}],
  } : {}),
  ...(showWorking ? {
    workingSidebar: [{type: 'autogenerated', dirName: 'working'}],
  } : {}),
};

export default sidebars;
